# -*- coding: utf-8 -*-
"""Yelp API.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I12XMFifwQvMRzQd_bDbEdlB-o72sJ__
"""

import requests
import json
import pandas as pd
from sqlalchemy import create_engine

api_key = '-bk173ZXSpMPGqt2Vikoi1KGv0HvZQnyjgBNVJQDz2VErJunSesmcpBalEEWo6dDkel4WcbFdORzQK668b5EPvTaUN7OXH_UrcE33LWmIgYDCGdLmPoVo_OmETNDXnYx'

headers = {'Authorization' : 'Bearer %s' % api_key}

businesses_api_url = 'https://api.yelp.com/v3/businesses/search'

#enter search parameters here
#location refer to area  code
params = {'term':'Recycling','location':'07101'}

business_request = requests.get(businesses_api_url, params=params, headers=headers)

business_request.text

decoded_businesses_request_text = json.loads(business_request.text)

decoded_businesses_request_text['businesses']

businesses = decoded_businesses_request_text['businesses']

type(businesses)

business_data = {
    'name' : [],
    'rating' : [],
    'price' : [],
    'address1': [],
    'address2' : [],
    'city' : [],
    'state' : [],
    'zip_code' : [],
    'phone' : [],
    'display_phone' : [],
    'review_count' : [],
    'transaction' : [],
    'url' : []
}

for business in businesses:
    name = business['name']
    business_data['name'].append(name)
    print(name)
    
    rating = business['rating']
    business_data['rating'].append(rating)
    print(rating)
    
    try:    
        price = business['price']
        business_data['price'].append(price)
        print(price)
    except:
        business_data['price'].append(0)
        print('no price info')
    
    address1 = business['location']['address1']
    business_data['address1'].append(address1)
    print(address1)
    
    address2 = business['location']['address2']
    business_data['address2'].append(address2)
    print(address2)
    
    city = business['location']['city']
    business_data['city'].append(city)
    print(city)
    
    state = business['location']['state']
    business_data['state'].append(state)
    print(state)
    
    zip_code = business['location']['zip_code']
    business_data['zip_code'].append(zip_code)
    print(zip_code)

    phone = business['phone']
    business_data['phone'].append(phone)
    print(phone)

    display_phone = business['display_phone']
    business_data['display_phone'].append(display_phone)
    print(display_phone)
  
    review_count = business['review_count']
    business_data['review_count'].append(review_count)
    print(review_count)
    
    transaction = business['transactions']
    business_data['transaction'].append(transaction)
    print(transaction)
    
    url = business['url']
    business_data['url'].append(url)
    print(url)
    
    print('--------------------------------------------')

business_data

df = pd.DataFrame(business_data)

df.head()

df.to_csv('yelp_restaurants_07101.csv', index = False)



